# -*- coding: utf-8 -*-
# Copyright 2022-Today TechKhedut.
# Part of TechKhedut. See LICENSE file for full copyright and licensing details.
{
    'name': "Agriculture Management | Agriculture ERP | Agriculture Integration | Farming Management",
    'version': "2.3",
    'description': """All in one agriculture management system""",
    'summary': "Agriculture Management",
    'author': 'TechKhedut Inc.',
    'category': 'Sales',
    'website': "https://techkhedut.com",
    'depends': ['mail', 'contacts', 'project', 'hr', 'product', 'stock', 'sale_management'],
    'data': [
        # Security
        'security/agriculture.security.xml',
        'security/ir.model.access.csv',

        # data
        'data/farm_type_data_views.xml',
        'data/weather_type_data.xml',
        'data/crop_incident_data_views.xml',
        'data/soil_indicator_data_view.xml',
        'data/water_indicator_data_view.xml',
        'data/sequence_views.xml',
        'data/cropping_types_data_views.xml',
        'data/product_service_data_views.xml',
        'data/equipment_tags_data_views.xml',        

        # Wizard
        'wizards/season_report_views.xml',
        'wizards/budget_vs_actual_spend_report_views.xml',
        'wizards/crop_fertiliser_bill_views.xml',
        'wizards/crop_pesticide_bill_views.xml',
        'wizards/crop_seed_bill_views.xml',
        'wizards/farm_equipment_bill_views.xml',
        'wizards/electricity_expense_bill_views.xml',
        'wizards/season_fleet_bill_views.xml',
        'wizards/farm_labour_bill_views.xml',
        'wizards/misc_expense_bill_views.xml',
        'wizards/crop_template_task_views.xml',
        'wizards/fertiliser_consume_order_views.xml',
        'wizards/pesticide_consume_order_views.xml',
        'wizards/seed_consume_order_views.xml',
        # Views
        'views/agriculture_farm_views.xml',
        'views/res_partner_inherit.xml',
        'views/agriculture_crop_views.xml',
        'views/crop_disease_views.xml',
        'views/agriculture_season_views.xml',
        'views/agriculture_financial_year_views.xml',
        'views/season_crop_views.xml',
        'views/farm_labour_views.xml',
        'views/farm_worker_views.xml',
        'views/farm_crop_disease_views.xml',
        'views/crop_pesticides_views.xml',
        'views/farm_crop_pesticides_views.xml',
        'views/crop_fertiliser_views.xml',
        'views/farm_crop_fertilizer_views.xml',
        'views/agriculture_equipment_views.xml',
        'views/farm_equipment_uses_views.xml',
        'views/soil_analysis_views.xml',
        'views/soil_indicators_views.xml',
        'views/soil_analysis_indicator_views.xml',
        'views/crop_production_views.xml',
        'views/misc_expense_views.xml',
        'views/agricultural_finance_views.xml',
        'views/farm_animal_views.xml',
        'views/farm_types_views.xml',
        'views/equipment_tags_views.xml',
        'views/agriculture_fleet_views.xml',
        'views/agriculture_warehouse_views.xml',
        'views/season_fleet_views.xml',
        'views/season_budget_views.xml',
        'views/crop_seed_views.xml',
        'views/farm_crop_seed_views.xml',
        'views/crop_healthy_manure_views.xml',
        'views/electricity_expense_views.xml',
        'views/weather_record_views.xml',
        'views/daily_weather_views.xml',
        'views/weather_type_views.xml',
        'views/crop_incident_views.xml',
        'views/season_crop_incident_views.xml',
        'views/water_analysis_views.xml',
        'views/water_analysis_indicator_views.xml',
        'views/water_indicator_views.xml',
        'views/field_visit_views.xml',
        'views/farmer_region_views.xml',
        'views/cropping_type_views.xml',
        'views/agriculture_task_views.xml',
        'views/model_views.xml',
        'views/task_template_views.xml',
        'views/reuse_template_details_views.xml',
        'views/stock_picking_inherit_views.xml',
        'report/soil_analysis_report.xml',
        'report/season_budget_report.xml',
        'report/weather_report.xml',
        'report/water_analysis_report.xml',
        'report/field_visit_report.xml',
        'views/templates.xml',
        # Menus
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'agriculture_management/static/src/xml/template.xml',
            'agriculture_management/static/src/scss/fonts.css',
            'agriculture_management/static/src/scss/style.scss',
            #'agriculture_management/static/src/js/lib/apexcharts.js',
            #'agriculture_management/static/src/js/lib/moment.min.js',
            'agriculture_management/static/src/js/dashboard/agriculture.js',
        ]
    },
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'OPL-1',
    'price': 349,
    'currency': 'USD',
}